"use client";

import { Recipe } from "@/data/food-types";
import { jsPDF } from "jspdf";
import { toast } from "sonner";
import { DayOfWeek, MealType } from "./useMealPlanner";

interface UseMealPlanPDFProps {
  days: { key: DayOfWeek; label: string }[];
  mealTypes: { key: MealType; label: string }[];
  plannedRecipes: Recipe[];
  getMeal: (day: DayOfWeek, mealType: MealType) => Recipe | null;
  totalMeals: number;
}

export function useMealPlanPDF({
  days,
  mealTypes,
  plannedRecipes,
  getMeal,
  totalMeals,
}: UseMealPlanPDFProps) {
  const downloadPDF = () => {
    if (totalMeals === 0) {
      toast.error("Add some meals to your plan first");
      return;
    }

    const doc = new jsPDF();
    let y = 15;
    const lineHeight = 8;
    const pageHeight = doc.internal.pageSize.height;

    const addLine = (text: string) => {
      if (y > pageHeight - 15) {
        doc.addPage();
        y = 15;
      }
      doc.text(text, 15, y);
      y += lineHeight;
    };

    // Title
    doc.setFontSize(16);
    addLine("🍽️ WEEKLY MEAL PLAN");

    doc.setFontSize(11);
    addLine("────────────────────────────────");

    days.forEach(day => {
      y += 4;
      doc.setFont("helvetica", "bold");
      addLine(day.label.toUpperCase());
      doc.setFont("helvetica", "normal");

      mealTypes.forEach(meal => {
        const recipe = getMeal(day.key, meal.key);
        addLine(
          recipe
            ? `• ${meal.label}: ${recipe.title} (${recipe.prepTime + recipe.cookTime} min)`
            : `• ${meal.label}: —`
        );
      });
    });

    // Ingredients
    y += 6;
    addLine("────────────────────────────────");
    doc.setFont("helvetica", "bold");
    addLine("🛒 INGREDIENTS NEEDED");
    doc.setFont("helvetica", "normal");

    const ingredients = new Map<string, { amount: number; unit: string }>();

    plannedRecipes.forEach(recipe => {
      recipe.ingredients.forEach((ing: any) => {
        if (ingredients.has(ing.item.name)) {
          ingredients.get(ing.item.name)!.amount += ing.amount;
        } else {
          ingredients.set(ing.item.name, {
            amount: ing.amount,
            unit: ing.item.unit,
          });
        }
      });
    });

    ingredients.forEach((value, name) => {
      addLine(`• ${value.amount} ${value.unit} ${name}`);
    });

    y += 6;
    addLine("Generated by PantryPal ❤️");

    doc.save(`meal-plan-${new Date().toISOString().split("T")[0]}.pdf`);
    toast.success("Meal plan downloaded!");
  };

  return { downloadPDF };
}
